### ISSUE TITLE
Remover arquivos desnecessários do projeto

### ISSUE THREAD

**Issue by RaulBSantos** [otopion/ponto-web#6]
Está show de bola o projeto! 
Alguns detalhes de organização poderiam ser aplicados para torná-lo mais fácil de manter e receber contribuições de outras pessoas.

Um deles é melhorar o `.gitignore`. Atualmente, os arquivos de cache que o Python gera estão versionados pastas `__pycache__`, o que causa transtornos quando outra pessoa tenta fazer o `git pull` para atualizar a cópia local do projeto. Tentei atualizar aqui e não consegui de primeira, terei que reverter todos esses arquivos antes, olha como fica:
![image](https://user-images.githubusercontent.com/14143674/86025574-beaf0c80-ba04-11ea-9bef-d7514cc3569a.png)

Um ponto interessante para considerar o que deve e o que não deve ser versionado é saber se determinado arquivo é referente ao projeto (deve ser versionado) ou se é referente ao ambiente (não deve ser versionado).

Por exemplo o arquivo `.python-version` diz respeito ao ambiente Python da máquina de cada um, e não deveria ser versionado.

Segue um [link](https://fjorgemota.com/gitignore-ou-como-ignorar-arquivos-no-git/) pra saber mais, qualquer coisa que eu puder ajudar, só falar

**Nota:** Como os arquivos já foram adicionados, além de serem incluídos ao gitignore, eles devem ser removidos do versionamento. O link acima explica como fazer

**Comment by otopion** [comment]
Show, obrigado pela dica.
